[package]
name = "ipld-schema"
version = "0.1.0"
authors = ["Sage Mitchell <dev@mx00s.com>"]
edition = "2018"
description = "ipld-schema mandatory description"
repository = "https://github.com/mx00s/ipld-schema"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
