[alias]
ft = "test --features fast-test"
lt = "test"
cov = "tarpaulin --ignore-tests --out Lcov --features fast-test"
ir = "insta review"
r = "run --features build-binary --bin ipld-schema"
w = "watch -c -x ir -x ft -x clippy -x doc"
