# assumes for the following crates are installed using `cargo install ...`
#
# - `cargo-do`
# - `cargo-insta`
# - `cargo-tarpaulin`
# - `cargo-watch`

[alias]
# run fast version of test suites
t = "do t-macros,t-schema"
t-macros = "test --manifest-path ./ipld-schema-macros/Cargo.toml --features fast-test"
t-schema = "test --manifest-path ./ipld-schema/Cargo.toml --features fast-test"

# code coverage
# (manually keep in sync with `./.gitlab/workflows/ci.yml`'s coverage job)
cov = "tarpaulin --ignore-tests --timeout 600 --out Lcov"

# review new/modified insta test snapshots
ir = "insta review"

# run the binary
r = "run --bin ipld-schema"

# watch test loop
w = "watch -c -x ir -x t -x clippy -x doc"

# pre-push (must clean before running clippy for reliable results)
p = "do fmt,test,clean,clippy"
